### ISSUE TITLE
Make Logger configurable

### ISSUE THREAD

**Issue by aklinkert** [jsimonetti/go-artnet#1]
Hi there,

I'm using you library to control lights on stage with my band, thanks a lot for building it! ❤️ As I'm running it as a subsystem of https://github.com/StageAutoControl/controller/ I'm experiencing some problems with debugging problems as I'm unfortunately unable to reduce the verbosity of go-artnet. I would like to suggest two changes:

* change log entries to be debug entries, normally you won't need them I guess. I'm seeing the following entries a lot:
  * "node started"
  * "packet send"
  * "received packet"
  * "added node"
* Make the package logger either injectable or configurable, for example as a exported variable that is accessible.

Does this sound reasonable to ya? Looking forward to your feedback!

Cheers,
Alex

_Edit:_
I'll fork the project and gonna try this out ;)

**Comment by jsimonetti** [comment]
Hi Alex,

It's nice to hear you can make good use of this package! I realise that some parts are very (maybe too) verbose.

I'd be happy to merge any changes regarding the verbosity aswell as a plugable logger. Looking forward to it!

Regards,
Jeroen
