### ISSUE TITLE
choose universe

### ISSUE THREAD

**Issue by noobusdeer** [jsimonetti/go-artnet#34]
I look at simple dmx examples, but how i can change from 0 to 1 universe

**Comment by aklinkert** [comment]
Hey @noobusdeer,

the second argument to [`SendDMXToAddress(dmx [512]byte, address Address)`](https://github.com/jsimonetti/go-artnet/blob/master/controller.go#L211) is the universe address. For translation from a `uint16` to a `artnet.Address` you can have a look at https://github.com/StageAutoControl/controller/blob/master/pkg/artnet/controller.go#L115.

Does this help?

Best,
Alex

**Comment by jsimonetti** [comment]
Closing this for now due to lack of response.
